version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: kotiks        
      MYSQL_USER: username            
      MYSQL_PASSWORD: password        
      MYSQL_ROOT_PASSWORD: root_password  
    volumes:
      - db_data:/var/lib/mysql      
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: